### ISSUE TITLE
MsgFactory Can be null in VciServerImpl

### ISSUE THREAD

**Issue by philip-culver** [hms-networks/ixxat-vci4-dotnet-wrapper#1]
In VciServerImpl::Initialize() if hVciLib is non null then the m_msgFactory class member variable is not initialized.  m_msgFactory is not a static member or singleton, but hVciLib is a global variable and m_msgFactory should be set outside of the hVciLib check.

This is in https://github.com/hms-networks/ixxat-vci4-dotnet-wrapper/blob/main/src/impl/vcinet.cpp Line 196.

**Comment by HMS-klob** [comment]
Thank you for reporting. Fixed in https://github.com/hms-networks/ixxat-vci4-dotnet-wrapper/commit/3104f5c9dcac301e5a8c917914587b515ddd3615
